name: Test

on:
  - pull_request
  - push

jobs:
  Types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: tsc

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx xo

  Firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: tsc
      - run: xvfb-run npm run test:gecko
        timeout-minutes: 2
      - run: echo "If tests timeout, there's likely an issue in the tests"

  Chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: tsc
      - run: xvfb-run npm run test:blink
        timeout-minutes: 2
      - run: echo "If tests timeout, there's likely an issue in the tests"
