name: Test

on:
  - pull_request
  - push

jobs:
  Types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: tsc

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx xo

  Firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: tsc
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum npm run test:gecko

  Chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: tsc
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum npm run test:blink
